version: "3"
services:
  spigotmc:
    image: "${DOCKER_HUB_USERNAME}/${IMG_PREFIX}spigot:${REV}"
    ports:
      - "${SERVER_PORT}:25565"
      # This has to be smarter, e.g. mount each file and sub_directories
    volumes:
      - ${PWD}/data/spigot:${SPIGOTDIR}

    environment:
      - EULA=true
      - XMS=${XMS}
      - XMX=${XMX}
      - FORCE_DOWNLOAD=false
      - BROADCAST_RCON_TO_OPS=${BROADCAST_RCON_TO_OPS}
      - VIEW_DISTANCE=${VIEW_DISTANCE}
      - MAX_BUILD_HEIGHT=${MAX_BUILD_HEIGHT}
      - SERVER_IP=${SERVER_IP}
      - LEVEL_SEED=${LEVEL_SEED}
      - RCON_PORT=${RCON_PORT}
      - GAMEMODE=${GAMEMODE}
      - SERVER_PORT=${SERVER_PORT}
      - ALLOW_NETHER=${ALLOW_NETHER}
      - ENABLE_COMMAND_BLOCK=${ENABLE_COMMAND_BLOCK}
      - ENABLE_RCON=${ENABLE_RCON}
      - ENABLE_QUERY=${ENABLE_QUERY}
      - OP_PERMISSION_LEVEL=${OP_PERMISSION_LEVEL}
      - PREVENT_PROXY_CONNECTIONS=${PREVENT_PROXY_CONNECTIONS}
      - GENERATOR_SETTINGS=${GENERATOR_SETTINGS}
      - RESOURCE_PACK=${RESOURCE_PACK}
      - LEVEL_NAME=${LEVEL_NAME}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - PLAYER_IDLE_TIMEOUT=${PLAYER_IDLE_TIMEOUT}
      - MOTD=${MOTD}
      - QUERY_PORT=${QUERY_PORT}
      - DEBUG=${DEBUG}
      - FORCE_GAMEMODE=${FORCE_GAMEMODE}
      - HARDCORE=${HARDCORE}
      - WHITE_LIST=${WHITE_LIST}
      - BROADCAST_CONSOLE_TO_OPS=${BROADCAST_CONSOLE_TO_OPS}
      - PVP=${PVP}
      - SPAWN_NPCS=${SPAWN_NPCS}
      - GENERATE_STRUCTURES=${GENERATE_STRUCTURES}
      - SPAWN_ANIMALS=${SPAWN_ANIMALS}
      - SNOOPER_ENABLED=${SNOOPER_ENABLED}
      - DIFFICULTY=${DIFFICULTY}
      - FUNCTION_PERMISSION_LEVEL=${FUNCTION_PERMISSION_LEVEL}
      - NETWORK_COMPRESSION_THRESHOLD=${NETWORK_COMPRESSION_THRESHOLD}
      - LEVEL_TYPE=${LEVEL_TYPE}
      - SPAWN_MONSTERS=${SPAWN_MONSTERS}
      - MAX_TICK_TIME=${MAX_TICK_TIME}
      - ENFORCE_WHITELIST=${ENFORCE_WHITELIST}
      - USE_NATIVE_TRANSPORT=${USE_NATIVE_TRANSPORT}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - RESOURCE_PACK_SHA1=${RESOURCE_PACK_SHA1}
      - SPAWN_PROTECTION=${SPAWN_PROTECTION}
      - ONLINE_MODE=${ONLINE_MODE}
      - ALLOW_FLIGHT=${ALLOW_FLIGHT}
      - MAX_WORLD_SIZE=${MAX_WORLD_SIZE}

  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    volumes:
      - ./bungeecord/config.yml:/server/config.yml
