FROM openjdk:11-jdk
RUN mkdir /bungeecord
RUN mkdir /bungeecord/downloads
RUN mkdir /bungeecord/server
RUN wget "https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar" -O /bungeecord/downloads/bungeecord.jar
